# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: "ubuntu-latest"
    mac:
      imageName: "macOS-latest"
    windows:
      imageName: "windows-latest"
  maxParallel: 3

pool:
  vmImage: windows-latest

steps:
- script: |
    cd ReflectionLoadTest
    dotnet build
  displayName: 'Build the project'

- script: |
    cd ReflectionLoadTest
    dotnet run
  displayName: 'Run the program'
  continueOnError: false

- script: |
    cd ReflectionLoadTest
    dotnet publish
  displayName: 'Release the program'
  continueOnError: false